### ISSUE TITLE
Beta Build Checklist

### ISSUE THREAD

**Issue by bilbaeno** [hp1932/cis510GameProject#31]
This list is to keep track of all the things that need to be completed for the beta build this Friday. I'll be filling it out during our Skype meeting tonight.
### Phase 1 - Simulation
- [x] Add customer satisfaction to UI
- [x] Customer speed up function
- [x] 
### Phase 2 - Report
- [x] Add customers served/missed and overall satisfaction to UI
- [x] 
- [x] 
### Phase 2b - Pricing
- [ ] Update UI to match project style
- [x] 
- [x] 
### Phase 2c - Purchasing
- [ ] Update UI to match project style
- [x] Link graph to Global economy values
- [x] 
### Overall
- [x] Economy
- [x] Option menu (mute music, mute sounds, restart, help text?)
- [ ] Rename scenes in Unity and adjust scripts to match

**Comment by bilbaeno** [comment]
Added "Rename scenes in Unity and adjust scripts to match" to the Overall header.

**Comment by hp1932** [comment]
The menu currently has a "mute audio" button, which mutes everything. I can change it later to be two buttons -- one that mutes music and one that mutes sounds.
