### ISSUE TITLE
Achievements - Overview

### ISSUE THREAD

**Issue by hp1932** [hp1932/cis510GameProject#42]
- [x] Issue #47 - Basic Structure
- [x] Issue #38 - Progress Checker 
- [x] Issue #39 - Pop-up for notification
- [ ] Issue #40 - Graph Implementation 
- [x] Issue #41 - Economy Implementation

**Comment by hp1932** [comment]
QUESTIONS:
1. What do the achievements do? Just adjust the graph and give the user something to strive for?
2. Can they ever be reverted? (i.e you get 100 customers, but then a few "days" later you drop the ball and that number drops back to 25. Should you still have the achievement and all it influences?)
3. Are they based only on cash in the bank? 
4. Do they also track max customers?
   Are these going to be custom achievements, or something we can make more dynamic like "Wow, you made it to X customers!" (so we'd just be tracking the max number of customers and the cash in the bank, then comparing them to a list of max numbers on a tier system?)

**Comment by solcjoye** [comment]
What do the achievements do? Just adjust the graph and give the user something to strive for?

**Ideally, reaching the next level of achievement would allow you to serve more customers (from 50 to 75 for example) and would allow you to charge more maybe?**

Can they ever be reverted? (i.e you get 100 customers, but then a few "days" later you drop the ball and that number drops back to 25. Should you still have the achievement and all it influences?)
Are they based only on cash in the bank?

**The achievement should not be based on cash, or at least cash alone... it should be based on a variable that calculates based on how happy customers have been, and maybe like mean profit over X days or something... so it aggregating based on several different criteria.**

Do they also track max customers? Are these going to be custom achievements, or something we can make more dynamic like "Wow, you made it to X customers!" (so we'd just be tracking the max number of customers and the cash in the bank, then comparing them to a list of max numbers on a tier system?)

**That'd be good, but I don't know if we'll have time? I could be like earning a badge or something?
Could be something where you cut to another scene and a badge is awarded depending on what you have achieved, and then it cuts back to game. In a menu you could click 'awards' or 'badges' and it shows which you've earned and which you haven't...**
